from enum import Enum


class KitTrait(Enum):
    unruly = "unruly"
    not_unruly = "-unruly"
    shy = "shy"
    not_shy = "-shy"
    impulsive = "impulsive"
    not_impulsive = "-impulsive"
    bullying = "bullying"
    not_bullying = "-bullying"
    attention_seeker = "attention-seeker"
    not_attention_seeker = "-attention-seeker"
    daydreamer = "daydreamer"
    not_daydreamer = "-daydreamer"
    charming = "charming"
    not_charming = "-charming"
    fearless = "fearless"
    not_fearless = "-fearless"
    skittish = "skittish"
    not_skittish = "-skittish"
    quiet = "quiet"
    not_quiet = "-quiet"
    self_conscious = "self-conscious"
    not_self_conscious = "-self-conscious"
    know_it_all = "know-it-all"
    not_know_it_all = "-know-it-all"
    sweet = "sweet"
    not_sweet = "-sweet"
    polite = "polite"
    not_polite = "-polite"
    bossy = "bossy"
    not_bossy = "-bossy"
    noisy = "noisy"
    not_noisy = "-noisy"

    smug = "smug"
    not_smug = "-smug"
    secretive = "secretive"
    not_secretive = "-secretive"
    manipulative = "manipulative"
    not_manipulative = "-manipulative"
    leader_like = "leader-like"
    not_leader_like = "-leader-like"
    passionate = "passionate"
    not_passionate = "-passionate"
    rebellious = "rebellious"
    not_rebellious = "-rebellious"
    honest = "honest"
    not_honest = "-honest"
